<?php

declare(strict_types=1);

namespace YiiRocks\Voyti\Form\Auth;

use YiiRocks\Recaptcha\RecaptchaV2Rule;
use YiiRocks\Recaptcha\RecaptchaV3Rule;
use YiiRocks\Voyti\ModuleConfig;
use Yiisoft\FormModel\FormModel;
use Yiisoft\Translator\TranslatorInterface;
use Yiisoft\Validator\Helper\ObjectParser;
use Yiisoft\Validator\Rule\Email;
use Yiisoft\Validator\Rule\Length;
use Yiisoft\Validator\Rule\Regex;
use Yiisoft\Validator\Rule\Required;
use Yiisoft\Validator\RulesProviderInterface;

final class RegistrationForm extends FormModel implements RulesProviderInterface
{

    #[Required]
    #[Email]
    #[Length(max: 255)]
    public string $email = '';

    public bool $gdprConsent = false;

    public string $gRecaptchaResponse = '';

    #[Length(min: 6, max: 72)]
    public string $password = '';
    #[Required]
    #[Length(min: 3, max: 255)]
    #[Regex(pattern: '/^[-a-zA-Z0-9_\.@]+$/')]
    public string $username = '';

    public function __construct(
        private readonly ModuleConfig $config,
        private readonly TranslatorInterface $translator,
    ) {
    }

    public function getAttributeLabels(): array
    {
        return [
            'username' => $this->translator->translate('voyti.view.username_label', category: 'voyti'),
            'email' => $this->translator->translate('voyti.view.email_label', category: 'voyti'),
            'password' => $this->translator->translate('voyti.view.password_label', category: 'voyti'),
            'gdprConsent' => $this->translator->translate('voyti.view.registration.gdpr_consent_label', category: 'voyti'),
        ];
    }

    #[\Override]
    public function getFormName(): string
    {
        return 'register';
    }

    #[\Override]
    public function getRules(): iterable
    {
        $parser = new ObjectParser($this);
        $rules = $parser->getRules();

        if ($this->config->recaptchaVersion !== null && class_exists(RecaptchaV3Rule::class)) {
            $ruleClass = $this->config->recaptchaVersion === 'v2'
                ? RecaptchaV2Rule::class
                : RecaptchaV3Rule::class;

            $params = [];
            if ($this->config->recaptchaVersion === 'v3') {
                $params['threshold'] = 0.5;
                $params['action'] = 'voyti_' . $this->getFormName();
            }

            $rules['gRecaptchaResponse'] = [new $ruleClass(...$params)];
        }

        return $rules;
    }

    public function isPasswordAutoGenerated(): bool
    {
        return $this->config->generatePasswords;
    }
}
