<?php

declare(strict_types=1);

namespace YiiRocks\Voyti\Model\Form\Auth;

use YiiRocks\Voyti\Helper\RecaptchaHelper;
use YiiRocks\Voyti\ModuleConfig;
use YiiRocks\Voyti\Validator\PasswordComplexityRule;
use Yiisoft\FormModel\FormModel;
use Yiisoft\Translator\TranslatorInterface;
use Yiisoft\Validator\Helper\ObjectParser;
use Yiisoft\Validator\Rule\CompareType;
use Yiisoft\Validator\Rule\Email;
use Yiisoft\Validator\Rule\Equal;
use Yiisoft\Validator\Rule\Length;
use Yiisoft\Validator\Rule\Regex;
use Yiisoft\Validator\Rule\Required;
use Yiisoft\Validator\Rule\TrueValue;
use Yiisoft\Validator\RulesProviderInterface;

final class RegistrationForm extends FormModel implements RulesProviderInterface
{
    #[Required]
    #[Email]
    #[Length(max: 255)]
    public string $email = '';

    public bool $gdprConsent = false;

    public string $gRecaptchaResponse = '';

    #[Length(min: 6, max: 72)]
    public string $password = '';
    #[Equal(targetProperty: 'password', strict: true, type: CompareType::STRING)]
    public string $passwordRepeat = '';
    #[Required]
    #[Length(min: 3, max: 255)]
    #[Regex(pattern: '/^[-a-zA-Z0-9_\.@]+$/')]
    public string $username = '';

    public function __construct(
        private readonly ModuleConfig $config,
        private readonly TranslatorInterface $translator,
    ) {
    }

    /**
     * @return string[]
     *
     * @psalm-return array{username: string, email: string, password: string, passwordRepeat: string, gdprConsent: string}
     */
    public function getAttributeLabels(): array
    {
        return [
            'username' => $this->translator->translate('voyti.view.username_label', category: 'voyti'),
            'email' => $this->translator->translate('voyti.view.email_label', category: 'voyti'),
            'password' => $this->translator->translate('voyti.view.password_label', category: 'voyti'),
            'passwordRepeat' => $this->translator->translate('voyti.view.password_repeat_label', category: 'voyti'),
            'gdprConsent' => $this->translator->translate(
                'voyti.view.registration.gdpr_consent_label',
                category: 'voyti',
            ),
        ];
    }

    /**
     * @return string
     *
     * @psalm-return 'register'
     */
    #[\Override]
    public function getFormName(): string
    {
        return 'register';
    }

    #[\Override]
    public function getPropertyLabels(): array
    {
        return $this->getAttributeLabels();
    }

    #[\Override]
    public function getRules(): iterable
    {
        $parser = new ObjectParser($this);
        $rules = $parser->getRules();

        /** @var list<\Yiisoft\Validator\RuleInterface> $passwordRules */
        $passwordRules = $rules['password'];
        $rules['password'] = array_merge($passwordRules, PasswordComplexityRule::rules($this->config, $this->translator));

        if ($this->config->enableGdprCompliance) {
            $rules['gdprConsent'] = [new TrueValue(trueValue: true)];
        }

        $recaptchaRules = RecaptchaHelper::rules($this->config, $this->getFormName());
        if ($recaptchaRules !== []) {
            $rules['gRecaptchaResponse'] = $recaptchaRules;
        }

        return $rules;
    }

    public function isPasswordAutoGenerated(): bool
    {
        return $this->config->generatePasswords;
    }
}
