<?php

declare(strict_types=1);

namespace YiiRocks\Voyti\Form;

use Yiisoft\FormModel\FormModel;
use Yiisoft\Validator\Helper\ObjectParser;
use Yiisoft\Validator\Rule\Email;
use Yiisoft\Validator\Rule\Length;
use Yiisoft\Validator\Rule\Regex;
use Yiisoft\Validator\Rule\Required;
use Yiisoft\Validator\RulesProviderInterface;
use YiiRocks\Voyti\ModuleConfig;

final class RegistrationForm extends FormModel implements RulesProviderInterface
{
    #[Required]
    #[Length(min: 3, max: 255)]
    #[Regex(pattern: '/^[-a-zA-Z0-9_\.@]+$/')]
    public string $username = '';

    #[Required]
    #[Email]
    #[Length(max: 255)]
    public string $email = '';

    #[Length(min: 6, max: 72)]
    public string $password = '';

    public bool $gdprConsent = false;

    public string $gRecaptchaResponse = '';

    public function __construct(
        private readonly ModuleConfig $config,
    ) {
    }

    public function getRules(): iterable
    {
        $parser = new ObjectParser($this);
        $rules = $parser->getRules();

        if ($this->config->recaptchaVersion !== null && class_exists(\YiiRocks\Recaptcha\RecaptchaV3Rule::class)) {
            $ruleClass = $this->config->recaptchaVersion === 'v2'
                ? \YiiRocks\Recaptcha\RecaptchaV2Rule::class
                : \YiiRocks\Recaptcha\RecaptchaV3Rule::class;

            $params = $this->config->recaptchaVersion === 'v3'
                ? ['threshold' => 0.5, 'action' => 'voyti_' . $this->getFormName()]
                : [];

            $rules['gRecaptchaResponse'] ??= [];
            $rules['gRecaptchaResponse'][] = new $ruleClass(...$params);
        }

        return $rules;
    }

    public function getAttributeLabels(): array
    {
        return [
            'username' => 'Username',
            'email' => 'Email',
            'password' => 'Password',
            'gdprConsent' => 'Data processing consent',
        ];
    }

    public function getFormName(): string
    {
        return 'register';
    }

    public function isPasswordAutoGenerated(): bool
    {
        return $this->config->generatePasswords;
    }
}
